apiVersion:  apps/v1 #Api version and kind
kind: ReplicaSet
metadata:                             # Metadata
  name: go-demo-2
spec:
  replicas: 2                          # Number of replicas we want
  selector:                           #All selectors MUST match the pods.
    matchLabels:
      type: backend                   # A number of pods labeled backend 
      service: go-demo-2
  template:
    metadata:
      labels:
        type: backend
        service: go-demo-2
        db: mongo
        language: go
    spec:
      containers:
      - name: db
        image: mongo:3.3
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: localhost
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
