resources:
- vscode.namespace.yaml
- vscode.deployment.yaml
- vscode.secret.yaml
- vscode.storage.yaml
- vscode.pv.yaml
- vscode.pvc.yaml
- vscode.ingress.yaml
- vscode.certificate.yaml
- vscode.issuer.yaml
