apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: vscode
spec:
  storageClassName: vscode.storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi