apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  type: LoadBalancer
#Source: https://github.com/devopsjourney1/mykustomapp/tree/master  