apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vscode-server-prod #This can not be in a patch specifically for namespaces

resources:
- ../../base

patches:
- path: vscode.prod.deployment.yaml
  target:
    kind: Deployment
- path: vscode.prod.secret.yaml
  target:
    kind: Secret    