apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vscode-letsencrypt-prod
  namespace: vscode
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: brandon@brandonwest.tech
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: vscode-letsencrypt-prod
    # ACME DNS-01 provider configurations
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector:
        dnsNames:
        - vscode-dev.diagon.cloud
      dns01:
        cloudflare:
          email: brandon@brandonwest.tech
          # !! Remember to create a k8s secret before
          # kubectl create secret generic cloudflare-api-key-secret
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
