apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: storage
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain 
  accessModes:
    - ReadWriteOnce
  local:
    path: /data-dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node3