bases:
- ../../base

namespace: dev

patchesStrategicMerge:
  - replicas.yaml #This has to match based on the name of the specific resource you're using and want to override.

configMapGenerator:
- name: mykustom-map
  env: .env