apiVersion: v1
kind: Pod
metadata:
  name: host-path
spec:
  containers:
    - name: busybox
      command: ['tail', '-f', '/dev/null']
      image: busybox
      volumeMounts:
        - name: data
          mountPath: /data #The container path
  volumes:
  - name: data
    hostPath:
      path: /home/caboose/demo/data #The host path 