#Original
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
  labels:
    app: mywebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: mywebapp
    tier: frontend
  type: LoadBalancer
#Source: https://github.com/devopsjourney1/mykustomapp/tree/master  


---
#Kustomize Version
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  type: LoadBalancer
#Source: https://github.com/devopsjourney1/mykustomapp/tree/master  