name: Update Commit Table

on:
  push:
    branches:
      - main  

jobs:
  update-commit-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Update Table"

      - name: Run update_table.sh for 100DaysOfKubernetes
        working-directory: 100DaysOfKubernetes
        run:  |
          ls -ltra  
          pwd
          bash ${{ github.workspace }}/.github/workflows/update_table.sh

      - name: Run update_table.sh for 100DaysOfProgramming/python
        working-directory: 100DaysOfProgramming/python
        run:  |
          ls -ltra  
          pwd
          bash ${{ github.workspace }}/.github/workflows/update_table.sh        