name: Update Commit Table

on: push

jobs:
  update-commit-table:
    runs-on: ubuntu-latest
    env:
      MAIN_DIRECTORY: ${{ github.workspace }}
      CI_COMMIT_MESSAGE: Git Actions Workflow - Update daily_commit_tracker
      CI_COMMIT_AUTHOR: BrandWest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: path filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            kubernetes:
              - '100DaysOfKubernetes/**'
            python:
              - '100DaysOfProgramming/python/**'
          
      - name: Run update_table.sh for 100DaysOfKubernetes
        if: steps.filter.outputs.kubernetes == 'true'
        working-directory: 100DaysOfKubernetes
        run:  |
          ls -ltra  
          pwd
          echo "${{ github. path }}"
          bash ${{ github.workspace }}/.github/workflows/update_table.sh kube

      - name: Run update_table.sh for 100DaysOfProgramming/python
        if: steps.filter.outputs.python == 'true'
        working-directory: 100DaysOfProgramming/python
        run:  |
          ls -ltra  
          pwd
          bash ${{ github.workspace }}/.github/workflows/update_table.sh python

      - name: Push new Daily_trackers Kubernetes
        if: ${{ steps.filter.outputs.kubernetes == 'true' }}
        run: |
          echo "Current dir: ${pwd}"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "brand.jwest@gmail.com"
          git add ${{ github.workspace }}/100DaysOfKubernetes/daily_commit_tracker.md 
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

      - name: Push new daily_commit_tracker.mds Python
        if: ${{ steps.filter.outputs.python == 'true' }}
        run: |
          echo "Current dir: ${pwd}"
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add ${{ github.workspace }}/100DaysOfProgramming/python/daily_commit_tracker.md 
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
