name: Update Commit Table

on:
  push:
    branches:
      - main  

jobs:
  update-commit-table:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Git Actions Workflow
      CI_COMMIT_AUTHOR: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update_table.sh for 100DaysOfKubernetes
        working-directory: 100DaysOfKubernetes
        run:  |
          ls -ltra  
          pwd
          bash ${{ github.workspace }}/.github/workflows/update_table.sh

      - name: Run update_table.sh for 100DaysOfProgramming/python
        working-directory: 100DaysOfProgramming/python
        run:  |
          ls -ltra  
          pwd
          bash ${{ github.workspace }}/.github/workflows/update_table.sh
      
      - name: Push new README.mds
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add README Tracker update
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
